In [1]:
import numpy as np

**Valid Sudoku**

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [8]:
c=np.sum(s,axis=1)
for i in c:
    if i!=45:
        print("Sudoku not valid")
else:
    print("Sudoku is valid")

Sudoku is valid


In [9]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("Sudoku not valid")
else:
    print("Sudoku is valid")

Sudoku is valid


In [10]:
r=s[0:3,0:3]
r

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [11]:
for i in range(0,9,3):
  for j in range(0,9,3):
      n=(s[i:i+3,j:j+3])
      print(n.sum())
      

45
45
45
45
45
45
45
45
45


**General Questions**

In [12]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [13]:
#Get the shape of the matrix.


In [14]:
data.shape

(5, 3)

In [15]:
#Find the average age of students.


In [16]:
avg_age=np.average(data[:,0])
avg_age

np.float64(18.4)

In [17]:
#Extract Math marks of all students.


In [18]:
marks=data[:,1]
marks

array([85, 92, 76, 65, 90])

In [19]:
#Find the highest Science mark.


In [20]:
max_s=np.max(data[:,2])
max_s

np.int64(95)

In [21]:
#Get details of the student who scored more than 90 in Math.



In [22]:
data[data[:,1]>90]




array([[19, 92, 88]])

In [23]:
#Increase Math marks of all students by 5.


In [24]:
data[:,1]+5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [25]:
#Find how many students are younger than 19.
#np.count_nonzero(data[:,0] <19)
len(data[data[:,0] <19])

3

In [26]:
#Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [27]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]


array([[19, 92, 88],
       [20, 90, 85]])

In [28]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])